### PR TITLE
Update to bazel 7.3.1

### PR DESCRIPTION
**Pull request by phoepsilonix**

### CODE REVIEW

**Comment by phoepsilonix** [comment]
It might be a good idea to migrate to branch/24.08.

**Comment by phoepsilonix** [comment]
Updated README.md.

The following is the approach as of bazel 7.3.1. It should be valid as long as the format of resolved.bzl doesn't change.
```sh
bazel build --nobuild --repository_cache="/path/to/cache" [--config config_name] --experimental_repository_resolved_file=resolved.bzl //path/to/target1:name //path/to/target2:name .. 
```
Process resolved.bzr with the sed command to make it easier to handle with the jq command.
```sh
sed -e 's/^resolved = //' -e 's/ False/ "False"/g' -e 's/ None/ "None"/g' resolved.bzl > resolved.json
```
Convert to JSON or YAML format that can be recognized by flatpak-builder.
```sh
jq -r '[ .[] | select(.repositories != null) | .repositories[] | select(.attributes.name != null) | select(.rule_class != null) | { url: ( if .attributes.url == "" then ( .attributes.urls[0] // "") else (.attributes.url // (.attributes.urls[0] // "")) end ), sha256: ( .attributes.sha256 // "" ), downloaded_file_path: ( .attributes.downloaded_file_path // null ), } | select(.url != "") | { type: "file", url: .url, dest: "bazel-deps", } + ( if .downloaded_file_path != "" and .downloaded_file_path != null then { "dest-filename": .downloaded_file_path, } else {} end ) + { sha256: .sha256, } ]' resolved.json > projects-deps.json
yq -y "." projects-deps.json > projects-deps.yaml
```
If the checksum(sha256) is missing, please update it separately.
Add either `- projects-deps.yaml` or `- projects-deps.json` to the sources.
```yaml
build-commands:
  - bazel build --distdir=$PWD/bazel-deps --registry=$PWD/bcr //path/to/target:name
sources:
  - type: git
    url: https://github.com/bazelbuild/bazel-central-registry.git
    branch: main
    dest: bcr
  - projects-deps.yaml
  ...

**Comment by phoepsilonix** [comment]
@flathubbot merge

**Comment by phoepsilonix** [comment]
@flathubbot review

**Comment by phoepsilonix** [comment]
@bbhtt @albert-tomanek @wengxt @flathubbot 
If there are no issues, please proceed with the merge.
I think it's a good idea to create a new branch called branch/24.08 and merge into it.

**Comment by bbhtt** [comment]
Done, thanks. This is without a maintainer now, if you want to maintain this please open an issue in https://github.com/flathub/flathub/issues

cc @wengxt if you want to as well ^^

**Comment by phoepsilonix** [comment]
Thank you!

**Comment by hfiguiere** [comment]
did you merge this in 24.08 while it still build 23.08?????

**Comment by bbhtt** [comment]
Looks like a overlook, I'll fix it.

**Pull request closed without merging**
