### PR TITLE
Acutually bump runtime to 24.08

### PR DESCRIPTION
**Pull request by bbhtt**

### CODE REVIEW

**Comment by phoepsilonix** [comment]
@bbhtt

If there are no issues, I'd like to switch the 23.08 branch to 7.3.1 as well.
This is because it would enable offline building of projects that depend on the 23.08 runtime and have adapted to bzlmod.

While sdk-extensions can be installed separately without problems, for some reason in my environment, I can't incorporate them using add-build-extensions. Does this require some ingenuity in formatting?

Should the update to 7.3.1 be done only for 24.08?

**Comment by bbhtt** [comment]
No, feel free to update it in 23.08 as well.

> While sdk-extensions can be installed separately without problems, for some reason in my environment, I can't incorporate them using add-build-extensions. Does this require some ingenuity in formatting?

Not really, what issues are you having ?

**Comment by phoepsilonix** [comment]
@bbhtt

Thank you for your response.

Even after adding to add-build-extension and searching multiple locations using commands like find within build-commands, the file cannot be found anywhere.

https://github.com/flathub/org.fcitx.Fcitx5.Addon.Mozc
```
Flatpak 1.15.10
flatpak-builder-1.4.4
```
I need both Qt6Core and Fcitx5Core, as well as bazel and llvm.
Currently, I'm placing Qt6Core by adding org.kde.Sdk to the sdk, and Fcitx5Core by adding org.fcitx.Fcitx5 to the runtime. 
I'm working around bazel by using GitHub releases.
Since org.fcitx.Fcitx5.Addon.Mozc is an addon extension of org.fcitx.Fcitx5, the runtime org.fcitx.Fcitx5 should be fixed.

I interpreted that adding org.freedesktop.Sdk.Extension.bazel to add-build-extension would make bazel available, but the bazel binary isn't deployed anywhere and can't be found with find.
If I add org.freedesktop.Sdk to sdk-extensions, of course bazel and llvm can be found. But this means removing org.kde.Sdk, so Qt6Core can't be found anymore. This is the problem I'm encountering.

However, since my environment has a mix of various flatpak applications and runtime versions, it might not be functioning as normally expected. I'm thinking it might be better to test in Docker or similar.

In any case, since you mentioned it's okay to update the version to 23.08, I'll update it soon.

**Comment by bbhtt** [comment]
Is this manifest working for you? Do you see the bazel version printed ?

Install the bazel extension first as these are not automatically installed: `flatpak install flathub org.freedesktop.Sdk.Extension.bazel//24.08` 

then build it: `flatpak-builder build --force-clean test.yaml`

```yaml
app-id: org.foo.bar
runtime: org.freedesktop.Sdk
runtime-version: "24.08"
sdk: org.freedesktop.Sdk
add-build-extensions:
  org.freedesktop.Sdk.Extension.bazel:
    directory: lib/sdk/bazel
    version: "24.08"
build-options:
  prepend-path: /usr/lib/sdk/bazel/bin
modules:
  - name: mozc
    buildsystem: simple
    build-commands:
      - ls -lA /usr/lib/sdk/bazel
      - bazel --version
```

**Comment by bbhtt** [comment]
The readme here needs a bit of correction https://github.com/flathub/org.freedesktop.Sdk.Extension.bazel/blob/1f0107d27e0f1b841c59331841862ad900bd2df5/README.md?plain=1#L8-L9 the format is supposed to be similar to `add-extensions`.

These 3 are needed at minimum:

```yaml
add-build-extensions:
  org.freedesktop.Sdk.Extension.bazel:
    directory: lib/sdk/bazel
    version: "24.08"
```

**Comment by phoepsilonix** [comment]
When executing test.yaml, bazel-7.3.1 was found.
However, when changing org.kde.Sdk to sdk, it can no longer be found.

```yml
app-id: org.foo.bar
runtime: org.freedesktop.Sdk
runtime-version: "24.08"
sdk: org.kde.Sdk//6.6
add-build-extensions:
  org.freedesktop.Sdk.Extension.bazel:
    directory: lib/sdk/bazel
    version: "24.08"
build-options:
  prepend-path: /usr/lib/sdk/bazel/bin
modules:
  - name: mozc
    buildsystem: simple
    build-commands:
      - ls -lA /usr/lib/sdk/bazel
      - bazel --version
```
```sh
ls -lA /usr/lib/sdk/bazel
ls: cannot access '/usr/lib/sdk/bazel': No such file or directory
```

**Comment by phoepsilonix** [comment]
```yml:test.yaml
app-id: org.foo.bar
runtime: org.freedesktop.Sdk
runtime-version: "24.08"
sdk: org.kde.Sdk//6.6
sdk-extensions:
  - org.freedesktop.Sdk.Extension.bazel
build-options:
  prepend-path: /usr/lib/sdk/bazel/bin
modules:
  - name: mozc
    buildsystem: simple
    build-commands:
      - ls -lA /usr/lib/sdk/bazel
      - bazel --version
```
```sh
flatpak-builder build --install-deps-from=flathub --force-clean test.yaml
```
```
Dependency Extension: org.freedesktop.Sdk.Extension.bazel 23.08
Updating org.freedesktop.Sdk.Extension.bazel/x86_64/23.08
Running: bazel --version
bazel 7.1.1
```

**Comment by phoepsilonix** [comment]
#16
Is it related?

**Comment by bbhtt** [comment]
6.6 is based on freedesktop-sdk 23.08 you have to match the versions.

**Comment by phoepsilonix** [comment]
In the end, does it mean that Bazel 24.08 cannot be used with org.kde.Sdk//6.6?
Does this mean that even with add-build-extensions, we can't use Bazel 24.08, which is a separate branch?

anyway, We can use the new version because the Bazel 23.08 branch has been updated.

**Comment by bbhtt** [comment]
> In the end, does it mean that Bazel 24.08 cannot be used with org.kde.Sdk//6.6?

Yea, you have to use the `branch/23.08` with KDE 6.6.

So basically:

```yaml
app-id: org.foo.bar
runtime: org.freedesktop.Sdk
runtime-version: "23.08"
sdk: org.freedesktop.Sdk
add-build-extensions:
  org.freedesktop.Sdk.Extension.bazel:
    directory: lib/sdk/bazel
    version: "23.08"
build-options:
  prepend-path: /usr/lib/sdk/bazel/bin
modules:
  - name: mozc
    buildsystem: simple
    build-commands:
      - ls -lA /usr/lib/sdk/bazel
      - bazel --version
```

**Comment by phoepsilonix** [comment]
However, it seems that we need to use 23.08 even with org.kde.Sdk//6.7.
If that's the case, then it's the same as using sdk-extensions.

**Comment by bbhtt** [comment]
Yes both KDE 6.6 and 6.7 are based on freedesktop runtime 23.08.

KDE 6.8 will be out in 2 months which will use freedesktop runtime 24.08. You can then use bazel 24.08 branch + KDE 6.8

**Comment by phoepsilonix** [comment]
I see.
In the future, if org.kde.Sdk is updated to 6.8, it means we'll be able to use freedesktop's 24.08.
Thanks to you, I was able to organize the information.
Thank you very much for teaching me various things.

**Comment by phoepsilonix** [comment]
Given the above situation, I think it was good that we updated the Bazel version in 23.08 to 7.3.1.

**Comment by bbhtt** [comment]
Yes you have to maintain exactly 2 branches of this extension synced with Freedesktop runtime releases. So 23.08 and 24.08 now.

**Comment by phoepsilonix** [comment]
I got it.

**Pull request merged**
